version: '3'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=dbsales
    ports:
      - "5432:5432"
    networks:
      - sales-project

  sales-proj-app:
    build: .
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - sales-project

networks:
  sales-project:
    driver: bridge
